# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Dititash"
license = "Private"
licenselink = ""
description = ""
homepage = ""
tags = []
features = []
min_version = "0.21"

[author]
  name = "Dimitri Torterat"
  homepage = "https://diti.me"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
